# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: godot-tester
      # You may pin to the exact commit or the version.
      # uses: croconut/godot-tester@8138293929bde928c05dde776b66ca50661ff4ee
      uses: croconut/godot-tester@v2.1a
      with:
        # Your Godot version number e.g. 3.2.2
        version: 3.3.3 # default is 3.2.2
        # Give relative path to your project.godot, if not in top level of repo
        path: ./Infinity\ Slasher # optional, default is ./
        # Test against mono version? Default: false
        is-mono: false # optional, default is false
        # How long to spend on importing assets, don't set if testing is not required
        import-time: 1 # optional, default is 1
        # How long the test should be run before it's timed out and fails
        test-timeout: 300 # optional, default is 300
        # Decimal value for minimum passing score e.g. if 88% of tests pass and minimum-pass is 0.8, then action passes.
        minimum-pass: 0.99 # optional, default is 0.99
